// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPt7IntIZLg10YJXKMslrjauL3dD6iVuc',
    appId: '1:85370425237:web:c0799888f475e2cde4f09c',
    messagingSenderId: '85370425237',
    projectId: 'mani-notes',
    authDomain: 'mani-notes.firebaseapp.com',
    storageBucket: 'mani-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkYfFVM8lR6z18mNMIniLHSSSDzzHcXXA',
    appId: '1:85370425237:android:004476b102f6edc7e4f09c',
    messagingSenderId: '85370425237',
    projectId: 'mani-notes',
    storageBucket: 'mani-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbILS2zeqjohYXwpTW0ZPRWV5-me0dKPI',
    appId: '1:85370425237:ios:f708c80440f14028e4f09c',
    messagingSenderId: '85370425237',
    projectId: 'mani-notes',
    storageBucket: 'mani-notes.appspot.com',
    iosClientId: '85370425237-tpp3efiobfk9oh9q09vincmad33e8r1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbILS2zeqjohYXwpTW0ZPRWV5-me0dKPI',
    appId: '1:85370425237:ios:f708c80440f14028e4f09c',
    messagingSenderId: '85370425237',
    projectId: 'mani-notes',
    storageBucket: 'mani-notes.appspot.com',
    iosClientId: '85370425237-tpp3efiobfk9oh9q09vincmad33e8r1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.learndart',
  );
}
